name: Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check

      - name: Build TypeScript
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Install mygit globally
        run: npm install -g .

      - name: Test mygit installation
        run: |
          # Test if mygit command runs
          mygit
